import type { Metadata } from "next";
import localFont from "next/font/local";
import { Header } from "./components/Header";
import "./globals.css";
import { Toaster } from 'sonner';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="">
          <div className="grid grid-rows-[auto_1fr_auto] h-screen items-center justify-items-center pb-15 xl:p-0 sm:p-0 font-[family-name:var(--font-geist-sans)]" >
            <Header />
            <main className="flex px-2 flex-col gap-8 row-start-2 items-center sm:items-start ">
              {children}
            </main>
              <Toaster richColors /> 
            <footer className="row-start-3 flex gap-6 flex-wrap items-center justify-center">
            </footer>
          </div>
        </div>

      </body>
    </html>
  );
}
